export const FETCH_BANNER = "FETCH_BANNER"; 
export const FETCH_BANNER_SUCCESS = "FETCH_BANNER_SUCCESS";
export const FETCH_BANNER_FAILURE = "FETCH_BANNER_FAILURE";


export const FETCH_SHOWCASE = "FETCH_SHOWCASE"; 
export const FETCH_SHOWCASE_SUCCESS = "FETCH_SHOWCASE_SUCCESS";
export const FETCH_SHOWCASE_FAILURE = "FETCH_SHOWCASE_FAILURE";