

export const FETCH_INVEST_DETAILS_CARD = "FETCH_INVEST_DETAILS_CARD";
export const FETCH_INVEST_DETAILS_CARD_SUCCESS = "FETCH_INVEST_DETAILS_CARD_SUCCESS";
export const FETCH_INVEST_DETAILS_CARD_FAILURE = "FETCH_INVEST_DETAILS_CARD_FAILURE";

export const FETCH_TABLEDATA = "FETCH_TABLEDATA";
export const FETCH_TABLEDATA_SUCCESS = "FETCH_TABLEDATA_SUCCESS";
export const FETCH_TABLEDATA_FAILURE = "FETCH_TABLEDATA_FAILURE";

// fetchSelectData
export const FETCH_SELECT_DATA = "FETCH_SELECT_DATA";
export const FETCH_SELECT_DATA_SUCCESS = "FETCH_SELECT_DATA_SUCCESS";
export const FETCH_SELECT_DATA_FAILURE = "FETCH_SELECT_DATA_FAILURE";


