export const FETCH_INVEST = "FETCH_INVEST"; 
export const FETCH_INVEST_SUCCESS = "FETCH_INVEST_SUCCESS";
export const FETCH_INVEST_FAILURE = "FETCH_INVEST_FAILURE";


export const FETCH_ISSUERS = "FETCH_ISSUERS"; 
export const FETCH_ISSUERS_SUCCESS = "FETCH_ISSUERS_SUCCESS";
export const FETCH_ISSUERS_FAILURE = "FETCH_ISSUERS_FAILURE";