

export const REQUEST_OTP_FOR_MOBILE = "REQUEST_OTP_FOR_MOBILE";
export const REQUEST_OTP_FOR_MOBILE_SUCCESS = "REQUEST_OTP_FOR_MOBILE_SUCCESS";
export const REQUEST_OTP_FOR_MOBILE_FAILURE = "REQUEST_OTP_FOR_MOBILE_FAILURE";
