export const GET_PERSONAL_INFO = "GET_PERSONAL_INFO";
export const GET_PERSONAL_INFO_SUCCESS = "GET_PERSONAL_INFO_SUCCESS";
export const GET_PERSONAL_INFO_FAILURE = "GET_PERSONAL_INFO_FAILURE";


export const UPDATE_PERSONAL_INFO = "UPDATE_PERSONAL_INFO";
export const UPDATE_PERSONAL_INFO_SUCCESS = "UPDATE_PERSONAL_INFO_SUCCESS";
export const UPDATE_PERSONAL_INFO_FAILURE = "UPDATE_PERSONAL_INFO_FAILURE";

// ============= ProfessionalDetails=============
export const GET_PROFESSIONAL_INFO = "GET_PROFESSIONAL_INFO";
export const GET_PROFESSIONAL_INFO_SUCCESS = "GET_PROFESSIONAL_INFO_SUCCESS";
export const GET_PROFESSIONAL_INFO_FAILURE = "GET_PROFESSIONAL_INFO_FAILURE";


export const GET_OCCUPATION_INFO = "GET_OCCUPATION_INFO";
export const GET_OCCUPATION_INFO_SUCCESS = "GET_OCCUPATION_INFO_SUCCESS";
export const GET_OCCUPATION_INFO_FAILURE = "GET_OCCUPATION_INFO_FAILURE";


export const GET_ANNUAL_INCOME_INFO = "GET_ANNUAL_INCOME_INFO";
export const GET_ANNUAL_INCOME_INFO_SUCCESS = "GET_ANNUAL_INCOME_INFO_SUCCESS";
export const GET_ANNUAL_INCOME_INFO_FAILURE = "GET_ANNUAL_INCOME_INFO_FAILURE";


export const GET_SOURCE_OF_INCOME_INFO = "GET_SOURCE_OF_INCOME_INFO";
export const GET_SOURCE_OF_INCOME_INFO_SUCCESS = "GET_SOURCE_OF_INCOME_INFO_SUCCESS";
export const GET_SOURCE_OF_INCOME_INFO_FAILURE = "GET_SOURCE_OF_INCOME_INFO_FAILURE";



export const UPDATE_PROFESSIONAL_INFO = "UPDATE_PROFESSIONAL_INFO";
export const UPDATE_PROFESSIONAL_INFO_SUCCESS = "UPDATE_PROFESSIONAL_INFO_SUCCESS";
export const UPDATE_PROFESSIONAL_INFO_FAILURE = "UPDATE_PROFESSIONAL_INFO_FAILURE";


// ===================== declaration ================
export const GET_DECLARATION_INFO = "GET_DECLARATION_INFO";
export const GET_DECLARATION_INFO_SUCCESS = "GET_DECLARATION_INFO_SUCCESS";
export const GET_DECLARATION_INFO_FAILURE = "GET_DECLARATION_INFO_FAILURE";

export const UPDATE_DECLARATION_INFO = "UPDATE_DECLARATION_INFO";
export const UPDATE_DECLARATION_INFO_SUCCESS = "UPDATE_DECLARATION_INFO_SUCCESS";
export const UPDATE_DECLARATION_INFO_FAILURE = "UPDATE_DECLARATION_INFO_FAILURE";