export const  VERIFY_MOBILE_WITH_OTP = "VERIFY_MOBILE_WITH_OTP";
export const VERIFY_MOBILE_WITH_OTP_SUCCESS = "VERIFY_MOBILE_WITH_OTP_SUCCESS";
export const VERIFY_MOBILE_WITH_OTP_FAILURE = "VERIFY_MOBILE_WITH_OTP_FAILURE";

export const VERIFY_MOBILE_RESEND_OTP = "VERIFY_MOBILE_RESEND_OTP";
export const VERIFY_MOBILE_RESEND_OTP_SUCCESS = "VERIFY_MOBILE_RESEND_OTP_SUCCESS";
export const VERIFY_MOBILE_RESEND_OTP_FAILURE = "VERIFY_MOBILE_RESEND_OTP_FAILURE";

